/**
 * Short affirmations for the sign-in card, rotated daily. The pool stays well
 * over one hundred lines so a frequent visitor keeps meeting new ones. Tone
 * rules: warm, plain language, energy-accounting friendly, never saccharine,
 * and no productivity guilt.
 */
export const AFFIRMATIONS: string[] = [
  "Your pace is a feature, not a flaw.",
  "Rest counts as progress.",
  "You are allowed to take up space.",
  "Small steps are still steps.",
  "Your brain is wired for wonder.",
  "Today does not need to be perfect.",
  "You have survived every hard day so far.",
  "Curiosity is your superpower.",
  "It is okay to do things differently.",
  "Your energy is worth budgeting.",
  "You notice things other people miss.",
  "Being gentle with yourself is productive.",
  "You do not have to earn rest.",
  "Your interests are worth your time.",
  "Slow days grow deep roots.",
  "You are more than your output.",
  "Asking for help is a skill, and you have it.",
  "Your sensitivity is a kind of intelligence.",
  "One thing at a time is a strategy.",
  "You are becoming, and becoming is messy.",
  "Your way of thinking builds new paths.",
  "Feeling a lot means you care a lot.",
  "You can begin again at any hour.",
  "Unfinished is not the same as failed.",
  "Your focus, when it lands, is dazzling.",
  "You are allowed to change your mind.",
  "Quiet effort still counts.",
  "Your needs are not too much.",
  "A soft start is still a start.",
  "You bring a perspective no one else has.",
  "Breaks are part of the work.",
  "You are doing better than you think.",
  "Your timing is your own.",
  "Every butterfly was once told to hurry.",
  "Stimming is self-care.",
  "You can be a work in progress and still be whole.",
  "Boundaries are a form of kindness to yourself.",
  "Your joy is worth protecting.",
  "Some days the win is showing up.",
  "You are not behind; you are on your own route.",
  "Detours find things highways miss.",
  "Your questions make rooms smarter.",
  "It is brave to try again.",
  "You deserve tools that fit your brain.",
  "Masking off is allowed here.",
  "Your rhythm matters more than the clock.",
  "Hard does not mean impossible.",
  "You have permission to be a beginner.",
  "Tiny rituals hold big days together.",
  "Your hyperfocus built something real.",
  "Recharging is not quitting.",
  "You can love the work and still need a break.",
  "Different is a direction, not a deficit.",
  "You are the expert on your own energy.",
  "Gentle is a valid speed.",
  "Your ideas deserve daylight.",
  "You can honor the plan and still improvise.",
  "Awkward moments fade; kindness stays.",
  "You are allowed to celebrate small wins loudly.",
  "The right people love how your mind works.",
  "You can put it down and pick it up tomorrow.",
  "Your worth is not a to-do list.",
  "Sensory breaks are wisdom, not weakness.",
  "You make hard things look quiet.",
  "Every draft counts as writing.",
  "Your attention is precious; spend it kindly.",
  "You have grown in ways no chart can show.",
  "Being early, late, or lost can still be on time for you.",
  "Your comfort object is doing great work.",
  "You can say no and still be generous.",
  "The spark you feel is worth following.",
  "You are not too sensitive; the world is loud.",
  "Half-speed still moves forward.",
  "You already carry everything you need to start.",
  "Naps are maintenance for brilliant machines.",
  "Your patterns make sense once someone listens.",
  "You are safe to be exactly this version of you.",
  "Missing a day does not erase a streak of trying.",
  "Your future self is rooting for you.",
  "It is okay to need more time.",
  "You translate between worlds every day.",
  "Comfort food, comfort show, comfort you: all valid.",
  "You can be tired and still be trying.",
  "Your softness has outlasted hard seasons.",
  "New systems take practice; so did walking.",
  "You are allowed to outgrow old expectations.",
  "The task will still be there after you breathe.",
  "You spot beauty in overlooked places.",
  "Doing it your way is doing it right.",
  "Your presence changes rooms for the better.",
  "You can start in the middle if the middle is easier.",
  "Little joys are load-bearing.",
  "You are a whole person, not a diagnosis.",
  "Your effort is visible to the people who matter.",
  "Some seasons are for cocooning.",
  "You get to define what a good day means.",
  "Your voice deserves the room's attention.",
  "Perfection is not on today's list.",
  "You have finished hard things before.",
  "Your calendar serves you, not the reverse.",
  "It is fine to feel two things at once.",
  "You are allowed to protect your morning.",
  "The world needs the thing only you would make.",
  "Your kindness to yourself teaches others how.",
  "You can trust the energy you wrote down.",
  "Wings take time; yours are already forming.",
];

/**
 * The day's affirmation: a deterministic daily rotation so the line feels
 * intentional rather than slot-machine random, and everyone on a device
 * shares the same one for the day.
 */
export function dailyAffirmation(now: Date = new Date()): string {
  // Key on the local calendar date so the line changes at the person's
  // midnight, not at UTC midnight.
  const dayKey = Math.floor(
    Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) / 86_400_000,
  );
  const len = AFFIRMATIONS.length;
  const index = ((dayKey % len) + len) % len;
  return AFFIRMATIONS[index] ?? AFFIRMATIONS[0]!;
}
